# CODE WRITTEN BY LAURA GOLEC FOR CSU33031 ASSIGNMENT 2

version: '2'
services:
  endpoint:
    build:
      dockerfile:
        endpoint/Dockerfile
    command: ["FFFFFF", "172.30.0.11", "172.30.16.4"]
    networks:
      cloud:
        ipv4_address: 172.30.16.4
    depends_on:
      - controller
    
  forwarder1:
    build:
      dockerfile:
        forwarder/Dockerfile
    command: ["AABBCC", "192.168.17.11", "129.144.50.11", "192.168.17.34", "129.144.50.22"]
    networks:
      home:
        ipv4_address: 192.168.17.34
      isp:
        ipv4_address: 129.144.50.22
    depends_on:
      - endpoint
      - controller

  forwarder2:
    build:
      dockerfile:
        forwarder/Dockerfile
    command: ["BBCCDD", "129.144.50.11", "172.30.0.11", "129.144.50.12", "172.30.0.254"]
    networks:
      isp:
        ipv4_address: 129.144.50.12
      cloud:
        ipv4_address: 172.30.0.254
    depends_on:
      - endpoint
      - controller

  forwarder3:
    build:
      dockerfile:
        forwarder/Dockerfile
    command: ["CCDDEE", "133.111.20.11", "172.30.0.11", "133.111.20.9", "172.30.0.32"]
    networks:
      home2:
        ipv4_address: 133.111.20.9
      cloud:
        ipv4_address: 172.30.0.32
    depends_on:
      - endpoint
      - controller

  user1:
    build:
      dockerfile:
        user/Dockerfile
    command: ["AAAAAA", "FFFFFF", "192.168.17.34", "192.168.17.11", "192.168.17.2"]
    networks: 
      home:
        ipv4_address: 192.168.17.2
    depends_on:
      - endpoint
      - forwarder1
      - forwarder2
      - forwarder3

  user2:
    build:
      dockerfile:
        user/Dockerfile
    command: ["AAAAAB", "AAAAAA", "133.111.20.9", "133.111.20.11", "133.111.20.3"]
    networks: 
      home2:
        ipv4_address: 133.111.20.3
    depends_on:
      - endpoint
      - forwarder1
      - forwarder2
      - forwarder3

  controller:
    build:
      dockerfile:
        controller/Dockerfile
    command: ["C0C0C0", "192.168.17.11", "172.30.0.11", "129.144.50.11", "133.111.20.11"]
    networks:
      home:
        ipv4_address: 192.168.17.11
      cloud:
        ipv4_address: 172.30.0.11
      isp:
        ipv4_address: 129.144.50.11
      home2:
        ipv4_address: 133.111.20.11

  tcpdump:
    image: kaazing/tcpdump
    network_mode: "host"
    volumes:
      - ./tcpdump:/tcpdump
    command: ["-i", "any", "udp", "-w", "tcpdump/tcpdump.pcap"]

networks:
  home:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.17.0/24
  cloud:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
  isp:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 129.144.50.0/16
  home2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 133.111.20.0/16