version: '3.7'
services:
  udpingress:
    build: ./ingress/
    container_name: udp_ingress
    network_mode: "host"
    volumes:
      - ./commonResources:/commonResources/commonFunctions

  udpclient:
    build: ./client/
    network_mode: "host"
    depends_on:
      - "udpingress"
      - "udpworker"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./endFiles:/endFiles

  udpworker:
    build: ./worker/
    network_mode: "host"
    depends_on:
      - "udpingress"
    deploy:
      mode: replicated
      replicas: 1

  tcpdump:
    image: kaazing/tcpdump
    network_mode: "host"
    volumes:
      - ./tcpdump:/tcpdump

volumes:
  commonResources:
    #read_only: true
