# CODE WRITTEN BY LAURA GOLEC FOR CSU33031 ASSIGNMENT 1

version: '3.7'
services:
  udpingress:
    build:
      dockerfile:
        ingress/Dockerfile
    container_name: udp_ingress
    network_mode: "host"

  udpclient:
    build:
      dockerfile:
        client/Dockerfile
    network_mode: "host"
    depends_on:
      - "udpingress"
      - "udpworker"
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - ./endFiles:/endFiles

  udpworker:
    build:
      dockerfile:
        worker/Dockerfile
    network_mode: "host"
    depends_on:
      - "udpingress"
    deploy:
      mode: replicated
      replicas: 3

  tcpdump:
    image: kaazing/tcpdump
    network_mode: "host"
    volumes:
      - ./tcpdump:/tcpdump

volumes:
  commonResources:
